apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-config
  namespace: distributed-systems
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables = {
      admin_credentials = "admin:admin"
      mysql_ifaces      = "0.0.0.0:6032"
    }

    mysql_variables = {
      threads           = 4
      max_connections   = 2048
      interfaces        = "0.0.0.0:6033"
      server_version    = "8.0.0"
      monitor_username  = "root"
      monitor_password  = "root"
      connect_timeout_server = 3000
    }

    mysql_servers = (
      {
        address         = "mysql"
        port            = 3306
        hostgroup       = 0
        status          = "ONLINE"
        max_connections = 80
      }
    )

    mysql_users = (
      {
        username          = "root"
        password          = "root"
        default_hostgroup = 0
        active            = 1
      }
    )
