apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
  namespace: distributed-systems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      containers:
        - name: proxysql
          image: proxysql/proxysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6033
              name: mysql
            - containerPort: 6032
              name: admin
          volumeMounts:
            - name: config
              mountPath: /etc/proxysql.cnf
              subPath: proxysql.cnf
          readinessProbe:
            tcpSocket:
              port: 6033
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: proxysql-config
