---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-trigger-secret
  namespace: distributed-systems
spec:
  encryptedData:
    RABBITMQ_URL: AgCThQ2PVDlBjYMLoFkXNWGTCN+a/1lDEaZetgkzzBtybV4M8RNx7kHHNWl+Ca/E9sNhXFR2Es06qSIU7m0LIStudaloBVpZQrnCjMASpjykZDumIyX7T9CBTpYkSk4oxYLueCd+Z8xn1DQKESij6h/tJxyl22A+sF18U58wctmHdzybvEOj/QTuutuxFRlNxozBgSnealQdjNcd/hVnT6bXI9lPKgcjhp6kk+qPzwEFBBihERC0CSVSQtSc96zFrc9nzvFmSOuFEmjsYzm0hcnRSJX+L+cm3fj+d62c4Zct/jaZh4CpZiYQG3jdDFFsHSLGYqUxsXVeQjkQg/Bdxzs++WGwncnCXMcaRVP5HELXTym8VZg/BYmEn45DAHJ36kK4SgYuhIFwmWAzaaSnPuJiuUh5l4DsEDByh2e2EA7LzF3EomLmL3Oyb929YjGjEX/k0atd/r1TTC4nvFUHf4SzDzg2TayY8aZK6xK7TNbml/x9WLnU5MM975/2Q41q8rRYIPYZKNLXTiy5EEZKOFzEfwOrSC66gE0ED1k4/3KnBmWvjDrzw3aRA/dzB4RGJEyHT1diqeIl8ADOdqhX8tzZhuXyE7yexG2DpavEAbzjf6/7Y+x+J2ZFSvIMrXZewp6tdfnYlQOdhbHkF6A2IKJnrwrAAx5abXJLYDtYO8wbvmYyxp5Jrm3bEdjNplF6ZkLGSeL3cXu6lOxrNCx1YpgFYmt3PZJk/Ohw91J5dWfKu2fZUlQ4fvl2Po4H/CihpwOh0kMy7L6d9LbrHTVJczmM2lJy0HIeG+o=
  template:
    metadata:
      name: rabbitmq-trigger-secret
      namespace: distributed-systems
    type: Opaque
