apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: distributed-systems
type: Opaque
stringData:
  DATABASE_URL: "mysql://root:root@mysql:3306/invoices"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  JWT_SECRET: "supersecret_changeme"
